import { ReactNode } from 'react';
import Head from 'next/head';

export const Layout = ({ children }: LayoutProps) => {
  return (
    <div className="min-h-screen bg-eerie-black">
      <Head>
        <title>Angel M. - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </div>
  );
};

type LayoutProps = {
  children: ReactNode;
};
