import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex items-center justify-center min-h-screen">
        <div className="container grid gap-20 grid-cols-2 px-24">
          <h1 className="text-white">Hello, World!</h1>
          <h1 className="text-white">Hello, World!</h1>
        </div>
      </section>
    </div>
  );
};

export default Home;
